Modified dir structure and (attempted) to create Makefile. The Makefile has issues when creating main and complains about an undefined reference to 'yyerror' 'yylex' and 'yyerror' from build/y.tab.o which is built from y.tab.c